### ISSUE TITLE
Why not copy file to alpha to make docker image size smaller?

### ISSUE THREAD

**Issue by SamYuan1990** [hyperledgendary/fabric-ccs-builder#3]
from a build image as golang and copy file to `/go/bin` ?

**Comment by mbwhite** [comment]
Yes could certainly do that;

This is intended as an example, so kept farily simple... but if you'd like make a PR :-)

**Comment by jt-nti** [comment]
Closing issues and archiving this repository now that the CCaaS builder has been added to the main fabric repository
